all:
	$(MAKE) -C address_book
	$(MAKE) -C hello_world
	$(MAKE) -C oneof
	$(MAKE) -C repeated

generate:
	$(MAKE) -C address_book generate
	$(MAKE) -C hello_world generate
	$(MAKE) -C oneof generate
	$(MAKE) -C repeated generate
