/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by pbtools.
 */

#include <dbg.h>
#include <Python.h>
#include "pbtools_py.h"
#include "c/hello_world.h"

static PyObject *py_hello_world_foo_encode(PyObject *module_p,
                                           PyObject *decoded_p)
{
    (void)module_p;

    struct hello_world_foo_t *message_p;
    void *workspace_p;
    PyObject *value_p;
    int res;

    res = pbtools_py_init((pbtools_py_new_t)hello_world_foo_new,
                          (void **)&message_p,
                          &workspace_p,
                          512);

    if (res != 0) {
        return (NULL);
    }

    value_p = PyDict_GetItemString(decoded_p, "bar");

    if (value_p != NULL) {
        res = pbtools_py_setint32(&message_p->bar, value_p);

        if (res != 0) {
            return (NULL);
        }
    }

    return (pbtools_py_encode((pbtools_py_encode_t)hello_world_foo_encode,
                              message_p,
                              128));
}

static PyObject *py_hello_world_foo_decode(PyObject *module_p,
                                           PyObject *bytes_p)
{
    (void)module_p;

    struct hello_world_foo_t *message_p;
    void *workspace_p;
    PyObject *decoded_p;
    PyObject *value_p;
    int res;

    res = pbtools_py_init((pbtools_py_new_t)hello_world_foo_new,
                          (void **)&message_p,
                          &workspace_p,
                          512);

    if (res != 0) {
        return (NULL);
    }

    res = pbtools_py_decode((pbtools_py_decode_t)hello_world_foo_decode,
                            message_p,
                            bytes_p);

    if (res < 0) {
        return (NULL);
    }

    decoded_p = PyDict_New();

    if (decoded_p == NULL) {
        return (NULL);
    }

    value_p = pbtools_py_getint32(message_p->bar);

    if (value_p == NULL) {
        return (NULL);
    }

    res = PyDict_SetItemString(decoded_p, "bar", value_p);

    if (res != 0) {
        return (NULL);
    }

    return (decoded_p);
}

static PyMethodDef methods[] = {
    {
        "foo_encode",
        (PyCFunction)py_hello_world_foo_encode,
        METH_O
    },
    {
        "foo_decode",
        (PyCFunction)py_hello_world_foo_decode,
        METH_O
    },
    { NULL }
};

static PyModuleDef module = {
    PyModuleDef_HEAD_INIT,
    .m_name = "hello_world",
    .m_doc = NULL,
    .m_size = -1,
    .m_methods = methods
};

PyMODINIT_FUNC PyInit_hello_world(void)
{
    PyObject *module_p;

    module_p = PyModule_Create(&module);

    if (module_p == NULL) {
        return (NULL);
    }

    return (module_p);
}
