/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by pbtools.
 */

#include <Python.h>
#include "pbtools_py.h"
#include "c/hello_world.h"

struct py_hello_world_foo_t {
    PyObject_HEAD
    struct hello_world_foo_t *message_p;
    void *workspace_p;
};

static int py_hello_world_foo_init(struct py_hello_world_foo_t *self_p)
{
    return (pbtools_py_init((pbtools_py_new_t)hello_world_foo_new,
                            (void **)&self_p->message_p,
                            &self_p->workspace_p,
                            64));
}

static PyObject *py_hello_world_foo_getbar(struct py_hello_world_foo_t *self_p)
{
    return (pbtools_py_getint32(self_p->message_p->bar));
}

static int py_hello_world_foo_setbar(struct py_hello_world_foo_t *self_p,
                                     PyObject *value_p)
{
    return (pbtools_py_setint32(&self_p->message_p->bar, value_p));
}

static PyGetSetDef py_hello_world_foo_getsetters[] = {
    {
        "bar",
        (getter)py_hello_world_foo_getbar,
        (setter)py_hello_world_foo_setbar,
        "bar",
        NULL
    },
    { NULL }
};

static PyObject *py_hello_world_foo_encode(struct py_hello_world_foo_t *self_p)
{
    return (pbtools_py_encode((pbtools_py_encode_t)hello_world_foo_encode,
                              self_p->message_p,
                              128));
}

static PyObject *py_hello_world_foo_decode(struct py_hello_world_foo_t *self_p,
                                           PyObject *bytes_p)
{
    return (pbtools_py_decode((pbtools_py_decode_t)hello_world_foo_decode,
                              self_p->message_p,
                              bytes_p));
}

static PyMethodDef py_hello_world_foo_methods[] = {
    {
        "encode",
        (PyCFunction)py_hello_world_foo_encode,
        METH_NOARGS
    },
    {
        "decode",
        (PyCFunction)py_hello_world_foo_decode,
        METH_O
    },
    { NULL }
};

static PyTypeObject py_hello_world_foo_type = {
    PyVarObject_HEAD_INIT(NULL, 0)
    .tp_name = "hello_world.Foo",
    .tp_basicsize = sizeof(struct py_hello_world_foo_t),
    .tp_itemsize = 0,
    .tp_flags = Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE,
    .tp_new = PyType_GenericNew,
    .tp_init = (initproc)py_hello_world_foo_init,
    .tp_methods = py_hello_world_foo_methods,
    .tp_getset = py_hello_world_foo_getsetters
};

static PyModuleDef module = {
    PyModuleDef_HEAD_INIT,
    .m_name = "hello_world",
    .m_doc = NULL,
    .m_size = -1,
    .m_methods = NULL
};

PyMODINIT_FUNC PyInit_hello_world(void)
{
    PyObject *module_p;

    if (PyType_Ready(&py_hello_world_foo_type) < 0) {
        return (NULL);
    }

    module_p = PyModule_Create(&module);

    if (module_p == NULL) {
        return (NULL);
    }

    Py_INCREF(&py_hello_world_foo_type);

    if (PyModule_AddObject(module_p,
                           "Foo",
                           (PyObject *)&py_hello_world_foo_type) < 0) {
        Py_DECREF(&py_hello_world_foo_type);
        Py_DECREF(module_p);

        return (NULL);
    }

    return (module_p);
}
