/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by pbtools version 0.1.0 Thu Jan 24 08:14:06 2019.
 */

#include <string.h>
#include <stdlib.h>
#include <assert.h>
#include <stdio.h>

#include "int32.h"

struct encoder_t {
    uint8_t *buf_p;
    int size;
    int pos;
};

struct decoder_t {
    const uint8_t *buf_p;
    int size;
    int pos;
    struct int32_heap_t *heap_p;
};

static struct int32_heap_t *heap_new(void *buf_p, size_t size)
{
    struct int32_heap_t *heap_p;

    if (size >= sizeof(*heap_p)) {
        heap_p = (struct int32_heap_t *)buf_p;
        heap_p->buf_p = buf_p;
        heap_p->size = size;
        heap_p->pos = sizeof(*heap_p);
    } else {
        heap_p = NULL;
    }

    return (heap_p);
}

static void *heap_alloc(struct int32_heap_t *self_p, size_t size)
{
    void *buf_p;
    int left;

    left = (self_p->size - self_p->pos);

    if (size <= left) {
        buf_p = &self_p->buf_p[self_p->pos];
        self_p->pos += size;
    } else {
        buf_p = NULL;
    }

    return (buf_p);
}

static void encoder_init(struct encoder_t *self_p,
                         uint8_t *buf_p,
                         size_t size)
{
    self_p->buf_p = buf_p;
    self_p->size = size;
    self_p->pos = (size - 1);
}

static size_t encoder_pos(struct encoder_t *self_p)
{
    return (self_p->pos);
}

static int encoder_get_result(struct encoder_t *self_p)
{
    int length;

    length = (self_p->size - self_p->pos - 1);
    memmove(self_p->buf_p,
            &self_p->buf_p[self_p->pos + 1],
            length);

    return (length);
}

static void encoder_prepend_byte(struct encoder_t *self_p,
                                 uint8_t value)
{
    if (self_p->pos < 0) {
        fprintf(stderr, "encoder_prepend_byte: %d\n", self_p->pos);
        exit(1);
    }

    self_p->buf_p[self_p->pos] = value;
    self_p->pos--;
}

static void encoder_prepend_bytes(struct encoder_t *self_p,
                                  const uint8_t *buf_p,
                                  size_t size)
{
    int i;

    for (i = (int)size - 1; i >= 0; i--) {
        encoder_prepend_byte(self_p, buf_p[i]);
    }
}

static void encoder_prepend_tag(struct encoder_t *self_p,
                                int tag,
                                int wire_type)
{
    encoder_prepend_byte(self_p, (tag << 3) | wire_type);
}

static void encoder_prepend_varint_value(struct encoder_t *self_p,
                                         uint64_t value)
{
    if (value > 127) {
        fprintf(stderr, "encoder_prepend_varint_value: %llu\n", (unsigned long long)value);
        exit(1);
    }

    encoder_prepend_byte(self_p, value);
}

static void encoder_prepend_varint(struct encoder_t *self_p,
                                   int tag,
                                   uint64_t value)
{
    encoder_prepend_varint_value(self_p, value);
    encoder_prepend_tag(self_p, tag, 0);
}

static void encoder_prepend_uint32(struct encoder_t *self_p,
                                   int tag,
                                   uint32_t value)
{
    if (value < (1 << 7)) {
        encoder_prepend_byte(self_p, value);
    } else if (value < (1 << 14)) {
        encoder_prepend_byte(self_p, value >> 7);
        encoder_prepend_byte(self_p, (value & 0x7f) | 0x80);
    } else if (value < (1 << 21)) {
        encoder_prepend_byte(self_p, value >> 14);
        encoder_prepend_byte(self_p, ((value >> 7) & 0x7f) | 0x80);
        encoder_prepend_byte(self_p, (value & 0x7f) | 0x80);
    } else if (value < (1 << 28)) {
        encoder_prepend_byte(self_p, value >> 21);
        encoder_prepend_byte(self_p, ((value >> 14) & 0x7f) | 0x80);
        encoder_prepend_byte(self_p, ((value >> 7) & 0x7f) | 0x80);
        encoder_prepend_byte(self_p, (value & 0x7f) | 0x80);
    } else {
        encoder_prepend_byte(self_p, value >> 28);
        encoder_prepend_byte(self_p, ((value >> 21) & 0x7f) | 0x80);
        encoder_prepend_byte(self_p, ((value >> 14) & 0x7f) | 0x80);
        encoder_prepend_byte(self_p, ((value >> 7) & 0x7f) | 0x80);
        encoder_prepend_byte(self_p, (value & 0x7f) | 0x80);
    }

    encoder_prepend_tag(self_p, tag, 0);
}

static void encoder_prepend_int32(struct encoder_t *self_p,
                                  int tag,
                                  int32_t value)
{
    if (value < 0) {
        encoder_prepend_byte(self_p, 0x01);
        encoder_prepend_byte(self_p, 0xff);
        encoder_prepend_byte(self_p, 0xff);
        encoder_prepend_byte(self_p, 0xff);
        encoder_prepend_byte(self_p, 0xff);
        encoder_prepend_byte(self_p, (value >> 28) | 0x80);
        encoder_prepend_byte(self_p, (value >> 21) | 0x80);
        encoder_prepend_byte(self_p, (value >> 14) | 0x80);
        encoder_prepend_byte(self_p, (value >> 7) | 0x80);
        encoder_prepend_byte(self_p, value | 0x80);
        encoder_prepend_tag(self_p, tag, 0);
    } else if (value > 0) {
        encoder_prepend_uint32(self_p, tag, (uint32_t)value);
    }
}

static void decoder_init(struct decoder_t *self_p,
                         const uint8_t *buf_p,
                         size_t size,
                         struct int32_heap_t *heap_p)
{
    self_p->buf_p = buf_p;
    self_p->size = size;
    self_p->pos = 0;
    self_p->heap_p = heap_p;
}

static void decoder_seek(struct decoder_t *self_p,
                         int offset)
{
    if (offset < 0) {
        exit(1);
    }

    self_p->pos += offset;
}

static int decoder_get_result(struct decoder_t *self_p)
{
    int res;

    if (self_p->pos == self_p->size) {
        res = self_p->pos;
    } else {
        res = -1;
    }

    //fprintf(stderr, "result: %d\n", res);

    return (res);
}

static uint8_t decoder_read_byte(struct decoder_t *self_p)
{
    uint8_t value;

    if (self_p->pos >= self_p->size) {
        fprintf(stderr, "decoder_read_byte: %d %d\n", self_p->pos, self_p->size);
        exit(1);
    }

    value = self_p->buf_p[self_p->pos];
    self_p->pos++;

    //fprintf(stderr, "r: %02x\n", value);

    return (value);
}

static void decoder_read_tag(struct decoder_t *self_p,
                             int tag,
                             int wire_type)
{
    uint8_t value;

    value = decoder_read_byte(self_p);

    if (value != ((tag << 3) | wire_type)) {
        fprintf(stderr, "decoder_read_tag: %02x %02x\n", value, (tag << 3) | wire_type);
        exit(1);
    }
}

static uint64_t decoder_read_varint_value(struct decoder_t *self_p)
{
    return (decoder_read_byte(self_p));
}

static uint64_t decoder_read_varint(struct decoder_t *self_p,
                                    int tag)
{
    decoder_read_tag(self_p, tag, 0);

    return (decoder_read_varint_value(self_p));
}

static int32_t decoder_read_int32(struct decoder_t *self_p,
                                  int tag)
{
    return (0);
}

struct int32_message_t *int32_message_new(
    void *workspace_p,
    size_t size)
{
    struct int32_message_t *message_p;
    struct int32_heap_t *heap_p;

    heap_p = heap_new(workspace_p, size);

    if (heap_p == NULL) {
        return (NULL);
    }

    message_p = heap_alloc(heap_p, sizeof(*message_p));

    if (message_p != NULL) {
        message_p->heap_p = heap_p;
        message_p->value = 0;
    }

    return (message_p);
}

void int32_message_encode_inner(
    struct encoder_t *encoder_p,
    struct int32_message_t *message_p)
{
    encoder_prepend_int32(encoder_p, 1, message_p->value);
}

void int32_message_decode_inner(
    struct decoder_t *decoder_p,
    struct int32_message_t *message_p)
{
    message_p->value = decoder_read_int32(decoder_p, 1);
}

int int32_message_encode(
    struct int32_message_t *message_p,
    uint8_t *encoded_p,
    size_t size)
{
    struct encoder_t encoder;

    encoder_init(&encoder, encoded_p, size);
    int32_message_encode_inner(&encoder, message_p);

    return (encoder_get_result(&encoder));
}

int int32_message_decode(
    struct int32_message_t *message_p,
    const uint8_t *encoded_p,
    size_t size)
{
    struct decoder_t decoder;

    decoder_init(&decoder, encoded_p, size, message_p->heap_p);
    int32_message_decode_inner(&decoder, message_p);

    return (decoder_get_result(&decoder));
}
