/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by pbtools.
 */

#ifndef NO_PACKAGE_H
#define NO_PACKAGE_H

#ifdef __cplusplus
extern "C" {
#endif

#include "pbtools.h"

/**
 * Enum M0.E1.
 */
enum m0_e1_e {
    m0_e1_b_e = 0,
    m0_e1_c_e = 1
};

/**
 * Message M0.M1.
 */
struct m0_m1_repeated_t {
    int length;
    struct m0_m1_t **items_pp;
    struct m0_m1_t *head_p;
    struct m0_m1_t *tail_p;
};

struct m0_m1_t {
    struct pbtools_message_base_t base;
    enum m0_e1_e v1;
};

/**
 * Message M0.
 */
struct m0_repeated_t {
    int length;
    struct m0_t **items_pp;
    struct m0_t *head_p;
    struct m0_t *tail_p;
};

struct m0_t {
    struct pbtools_message_base_t base;
    struct m0_m1_t v1;
    struct m0_m1_repeated_t v2;
    enum m0_e1_e v3;
};

int m0_v2_alloc(
    struct m0_t *self_p,
    int length);

/**
 * Encoding and decoding of M0.
 */
struct m0_t *
m0_new(
    void *workspace_p,
    size_t size);

int m0_encode(
    struct m0_t *self_p,
    uint8_t *encoded_p,
    size_t size);

int m0_decode(
    struct m0_t *self_p,
    const uint8_t *encoded_p,
    size_t size);

/* Internal functions. Do not use! */

void m0_init(
    struct m0_t *self_p,
    struct pbtools_heap_t *heap_p,
    struct m0_t *next_p);

void m0_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct m0_t *self_p);

void m0_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct m0_t *self_p);

void m0_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct m0_repeated_t *repeated_p);

void m0_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    int wire_type,
    struct m0_repeated_t *repeated_p);

void m0_finalize_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct m0_repeated_t *repeated_p);

void m0_m1_init(
    struct m0_m1_t *self_p,
    struct pbtools_heap_t *heap_p,
    struct m0_m1_t *next_p);

void m0_m1_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct m0_m1_t *self_p);

void m0_m1_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct m0_m1_t *self_p);

void m0_m1_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct m0_m1_repeated_t *repeated_p);

void m0_m1_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    int wire_type,
    struct m0_m1_repeated_t *repeated_p);

void m0_m1_finalize_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct m0_m1_repeated_t *repeated_p);

#ifdef __cplusplus
}
#endif

#endif
