/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by pbtools.
 */

#include <limits.h>
#include "optional_fields.h"

#if CHAR_BIT != 8
#    error "Number of bits in a char must be 8."
#endif

void optional_fields_message_init(
    struct optional_fields_message_t *self_p,
    struct pbtools_heap_t *heap_p)
{
    self_p->base.heap_p = heap_p;
    self_p->v1.is_present = false;
    self_p->v2.is_present = false;
    self_p->v3.is_present = false;
    self_p->v4 = 0;
    self_p->v5.is_present = false;
    self_p->v6.is_present = false;
}

void optional_fields_message_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct optional_fields_message_t *self_p)
{
    if (self_p->v6.is_present) {
        pbtools_encoder_write_enum_always(encoder_p, 6, self_p->v6.value);
    }
    if (self_p->v5.is_present) {
        pbtools_encoder_write_bytes_always(encoder_p, 5, &self_p->v5.value);
    }
    pbtools_encoder_write_int32(encoder_p, 4, self_p->v4);
    if (self_p->v3.is_present) {
        pbtools_encoder_write_string_always(encoder_p, 3, self_p->v3.value_p);
    }
    if (self_p->v2.is_present) {
        pbtools_encoder_write_bool_always(encoder_p, 2, self_p->v2.value);
    }
    if (self_p->v1.is_present) {
        pbtools_encoder_write_int32_always(encoder_p, 1, self_p->v1.value);
    }
}

void optional_fields_message_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct optional_fields_message_t *self_p)
{
    int wire_type;

    while (pbtools_decoder_available(decoder_p)) {
        switch (pbtools_decoder_read_tag(decoder_p, &wire_type)) {

        case 1:
            self_p->v1.is_present = true;
            self_p->v1.value = pbtools_decoder_read_int32(decoder_p, wire_type);
            break;

        case 2:
            self_p->v2.is_present = true;
            self_p->v2.value = pbtools_decoder_read_bool(decoder_p, wire_type);
            break;

        case 3:
            self_p->v3.is_present = true;
            pbtools_decoder_read_string(decoder_p, wire_type, &self_p->v3.value_p);
            break;

        case 4:
            self_p->v4 = pbtools_decoder_read_int32(decoder_p, wire_type);
            break;

        case 5:
            self_p->v5.is_present = true;
            pbtools_decoder_read_bytes(decoder_p, wire_type, &self_p->v5.value);
            break;

        case 6:
            self_p->v6.is_present = true;
            self_p->v6.value = pbtools_decoder_read_enum(decoder_p, wire_type);
            break;

        default:
            pbtools_decoder_skip_field(decoder_p, wire_type);
            break;
        }
    }
}

void optional_fields_message_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct optional_fields_message_repeated_t *repeated_p)
{
    pbtools_encode_repeated_inner(
        encoder_p,
        field_number,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct optional_fields_message_t),
        (pbtools_message_encode_inner_t)optional_fields_message_encode_inner);
}

void optional_fields_message_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct optional_fields_message_repeated_t *repeated_p)
{
    pbtools_decode_repeated_inner(
        decoder_p,
        repeated_info_p,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct optional_fields_message_t),
        (pbtools_message_init_t)optional_fields_message_init,
        (pbtools_message_decode_inner_t)optional_fields_message_decode_inner);
}

struct optional_fields_message_t *
optional_fields_message_new(
    void *workspace_p,
    size_t size)
{
    return (pbtools_message_new(
                workspace_p,
                size,
                sizeof(struct optional_fields_message_t),
                (pbtools_message_init_t)optional_fields_message_init));
}

int optional_fields_message_encode(
    struct optional_fields_message_t *self_p,
    uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_encode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_encode_inner_t)optional_fields_message_encode_inner));
}

int optional_fields_message_decode(
    struct optional_fields_message_t *self_p,
    const uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_decode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_decode_inner_t)optional_fields_message_decode_inner));
}
