/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by pbtools version 0.2.0 Tue Aug 27 22:08:14 2019.
 */

#include <string.h>

#include "repeated.h"

int repeated_message_int32s_alloc(
    struct repeated_message_t *self_p,
    int length)
{
    int res;
    int i;
    struct pbtools_int32_t *items_p;

    res = -1;
    self_p->int32s.items_pp = pbtools_heap_alloc(
        self_p->heap_p,
        sizeof(items_p) * length);

    if (self_p->int32s.items_pp != NULL) {
        items_p = pbtools_heap_alloc(self_p->heap_p, sizeof(*items_p) * length);

        if (items_p != NULL) {
            for (i = 0; i < length; i++) {
                items_p[i].value = 0;
                items_p[i].next_p = &items_p[i + 1];
                self_p->int32s.items_pp[i] = &items_p[i];
            }

            items_p[length - 1].next_p = NULL;
            self_p->int32s.length = length;
            self_p->int32s.head_p = &items_p[0];
            self_p->int32s.tail_p = &items_p[i];
            res = 0;
        }
    }

    return (res);
}

static void repeated_message_encode_inner(
    struct repeated_message_t *self_p,
    struct pbtools_encoder_t *encoder_p)
{
    int i;
    int pos;

    pos = encoder_p->pos;

    for (i = self_p->int32s.length - 1; i >= 0; i--) {
        pbtools_encoder_write_varint(encoder_p,
                                     self_p->int32s.items_pp[i]->value);
    }

    pbtools_encoder_write_tagged_varint(encoder_p, 1, 2, pos - encoder_p->pos);

    /* for (i = 0; i < self_p->strings.length; i++) { */
    /*     pbtools_encoder_write_string(encoder_p, 3, self_p->strings.items_pp[i]); */
    /* } */

    /* for (i = 0; i < self_p->bytes.length; i++) { */
    /*     pbtools_encoder_write_bytes(encoder_p, 4, &self_p->bytes.items_p[i]); */
    /* } */
}
#include "stdio.h"
static void repeated_message_decode_inner(
    struct repeated_message_t *self_p,
    struct pbtools_decoder_t *decoder_p)
{
    int wire_type;
    size_t size;
    int pos;
    struct pbtools_int32_t *item_p;
    int i;

    while (pbtools_decoder_available(decoder_p)) {
        switch (pbtools_decoder_read_tag(decoder_p, &wire_type)) {

        case 1:
            size = pbtools_decoder_read_varint_todo(decoder_p, wire_type, 2);
            pos = decoder_p->pos;

            while (decoder_p->pos < pos + size) {
                item_p = pbtools_heap_alloc(self_p->heap_p, sizeof(*item_p));

                if (item_p == NULL) {
                    pbtools_decoder_abort(decoder_p, PBTOOLS_OUT_OF_MEMORY);

                    return;
                }

                item_p->value = pbtools_decoder_read_varint_value(decoder_p);
                item_p->next_p = NULL;

                if (self_p->int32s.length == 0) {
                    self_p->int32s.head_p = item_p;
                } else {
                    self_p->int32s.tail_p->next_p = item_p;
                }

                self_p->int32s.tail_p = item_p;
                self_p->int32s.length++;
            }

            break;

        case 3:
            // self_p->strings_p = pbtools_decoder_read_string(decoder_p, wire_type);
            break;

        case 4:
            // pbtools_decoder_read_bytes(decoder_p, wire_type, &self_p->bytes);
            break;

        default:
            break;
        }
    }

    if (self_p->int32s.length > 0) {
        self_p->int32s.items_pp = pbtools_heap_alloc(
            self_p->heap_p,
            sizeof(item_p) * self_p->int32s.length);

        if (self_p->int32s.items_pp == NULL) {
            pbtools_decoder_abort(decoder_p, PBTOOLS_OUT_OF_MEMORY);

            return;
        }

        item_p = self_p->int32s.head_p;

        for (i = 0; i < self_p->int32s.length; i++) {
            self_p->int32s.items_pp[i] = item_p;
            item_p = item_p->next_p;
        }
    }
}

struct repeated_message_t *repeated_message_new(
    void *workspace_p,
    size_t size)
{
    struct repeated_message_t *self_p;
    struct pbtools_heap_t *heap_p;

    heap_p = pbtools_heap_new(workspace_p, size);

    if (heap_p == NULL) {
        return (NULL);
    }

    self_p = pbtools_heap_alloc(heap_p, sizeof(*self_p));

    if (self_p != NULL) {
        self_p->heap_p = heap_p;
        self_p->int32s.length = 0;
        self_p->messages.length = 0;
        self_p->strings.length = 0;
        self_p->bytes.length = 0;
    }

    return (self_p);
}

int repeated_message_encode(
    struct repeated_message_t *self_p,
    uint8_t *encoded_p,
    size_t size)
{
    struct pbtools_encoder_t encoder;

    pbtools_encoder_init(&encoder, encoded_p, size);
    repeated_message_encode_inner(self_p, &encoder);

    return (pbtools_encoder_get_result(&encoder));
}

int repeated_message_decode(
    struct repeated_message_t *self_p,
    const uint8_t *encoded_p,
    size_t size)
{
    struct pbtools_decoder_t decoder;

    pbtools_decoder_init(&decoder, encoded_p, size, self_p->heap_p);
    repeated_message_decode_inner(self_p, &decoder);

    return (pbtools_decoder_get_result(&decoder));
}
