/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by pbtools.
 */

#include <limits.h>
#include "sub_message_pointers_message.h"

#if CHAR_BIT != 8
#    error "Number of bits in a char must be 8."
#endif

void sub_message_pointers_message_foo_init(
    struct sub_message_pointers_message_foo_t *self_p,
    struct pbtools_heap_t *heap_p)
{
    self_p->base.heap_p = heap_p;

}

void sub_message_pointers_message_foo_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct sub_message_pointers_message_foo_t *self_p)
{
    (void)encoder_p;
    (void)self_p;
}

void sub_message_pointers_message_foo_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct sub_message_pointers_message_foo_t *self_p)
{
    (void)self_p;

    int wire_type;

    while (pbtools_decoder_available(decoder_p)) {
        switch (pbtools_decoder_read_tag(decoder_p, &wire_type)) {


        default:
            pbtools_decoder_skip_field(decoder_p, wire_type);
            break;
        }
    }
}

void sub_message_pointers_message_foo_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct sub_message_pointers_message_foo_repeated_t *repeated_p)
{
    pbtools_encode_repeated_inner(
        encoder_p,
        field_number,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct sub_message_pointers_message_foo_t),
        (pbtools_message_encode_inner_t)sub_message_pointers_message_foo_encode_inner);
}

void sub_message_pointers_message_foo_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct sub_message_pointers_message_foo_repeated_t *repeated_p)
{
    pbtools_decode_repeated_inner(
        decoder_p,
        repeated_info_p,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct sub_message_pointers_message_foo_t),
        (pbtools_message_init_t)sub_message_pointers_message_foo_init,
        (pbtools_message_decode_inner_t)sub_message_pointers_message_foo_decode_inner);
}

struct sub_message_pointers_message_foo_t *
sub_message_pointers_message_foo_new(
    void *workspace_p,
    size_t size)
{
    return (pbtools_message_new(
                workspace_p,
                size,
                sizeof(struct sub_message_pointers_message_foo_t),
                (pbtools_message_init_t)sub_message_pointers_message_foo_init));
}

int sub_message_pointers_message_foo_encode(
    struct sub_message_pointers_message_foo_t *self_p,
    uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_encode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_encode_inner_t)sub_message_pointers_message_foo_encode_inner));
}

int sub_message_pointers_message_foo_decode(
    struct sub_message_pointers_message_foo_t *self_p,
    const uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_decode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_decode_inner_t)sub_message_pointers_message_foo_decode_inner));
}

void sub_message_pointers_message_bar_init(
    struct sub_message_pointers_message_bar_t *self_p,
    struct pbtools_heap_t *heap_p)
{
    self_p->base.heap_p = heap_p;
    self_p->fie = 0;
}

void sub_message_pointers_message_bar_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct sub_message_pointers_message_bar_t *self_p)
{
    pbtools_encoder_write_int32(encoder_p, 333, self_p->fie);
}

void sub_message_pointers_message_bar_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct sub_message_pointers_message_bar_t *self_p)
{
    int wire_type;

    while (pbtools_decoder_available(decoder_p)) {
        switch (pbtools_decoder_read_tag(decoder_p, &wire_type)) {

        case 333:
            self_p->fie = pbtools_decoder_read_int32(decoder_p, wire_type);
            break;

        default:
            pbtools_decoder_skip_field(decoder_p, wire_type);
            break;
        }
    }
}

void sub_message_pointers_message_bar_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct sub_message_pointers_message_bar_repeated_t *repeated_p)
{
    pbtools_encode_repeated_inner(
        encoder_p,
        field_number,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct sub_message_pointers_message_bar_t),
        (pbtools_message_encode_inner_t)sub_message_pointers_message_bar_encode_inner);
}

void sub_message_pointers_message_bar_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct sub_message_pointers_message_bar_repeated_t *repeated_p)
{
    pbtools_decode_repeated_inner(
        decoder_p,
        repeated_info_p,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct sub_message_pointers_message_bar_t),
        (pbtools_message_init_t)sub_message_pointers_message_bar_init,
        (pbtools_message_decode_inner_t)sub_message_pointers_message_bar_decode_inner);
}

struct sub_message_pointers_message_bar_t *
sub_message_pointers_message_bar_new(
    void *workspace_p,
    size_t size)
{
    return (pbtools_message_new(
                workspace_p,
                size,
                sizeof(struct sub_message_pointers_message_bar_t),
                (pbtools_message_init_t)sub_message_pointers_message_bar_init));
}

int sub_message_pointers_message_bar_encode(
    struct sub_message_pointers_message_bar_t *self_p,
    uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_encode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_encode_inner_t)sub_message_pointers_message_bar_encode_inner));
}

int sub_message_pointers_message_bar_decode(
    struct sub_message_pointers_message_bar_t *self_p,
    const uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_decode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_decode_inner_t)sub_message_pointers_message_bar_decode_inner));
}

void sub_message_pointers_message_message_fie_foo_init(
    struct sub_message_pointers_message_message_fie_foo_t *self_p,
    struct pbtools_heap_t *heap_p)
{
    self_p->base.heap_p = heap_p;
    self_p->value = 0;
    self_p->bar_p = NULL;
}

void sub_message_pointers_message_message_fie_foo_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct sub_message_pointers_message_message_fie_foo_t *self_p)
{
    pbtools_encoder_sub_message_pointer_encode(
        encoder_p,
        1,
        (struct pbtools_message_base_t *)self_p->bar_p,
        (pbtools_message_encode_inner_t)sub_message_pointers_message_bar_encode_inner);
    pbtools_encoder_write_bool(encoder_p, 5, self_p->value);
}

void sub_message_pointers_message_message_fie_foo_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct sub_message_pointers_message_message_fie_foo_t *self_p)
{
    int wire_type;

    while (pbtools_decoder_available(decoder_p)) {
        switch (pbtools_decoder_read_tag(decoder_p, &wire_type)) {

        case 5:
            self_p->value = pbtools_decoder_read_bool(decoder_p, wire_type);
            break;

        case 1:
            pbtools_decoder_sub_message_pointer_decode(
                decoder_p,
                wire_type,
                (struct pbtools_message_base_t **)&self_p->bar_p,
                sizeof(struct sub_message_pointers_message_bar_t),
                (pbtools_message_init_t)sub_message_pointers_message_bar_init,
                (pbtools_message_decode_inner_t)sub_message_pointers_message_bar_decode_inner);
            break;

        default:
            pbtools_decoder_skip_field(decoder_p, wire_type);
            break;
        }
    }
}

int sub_message_pointers_message_message_fie_foo_bar_alloc(
    struct sub_message_pointers_message_message_fie_foo_t *self_p)
{
    return (pbtools_sub_message_alloc(
                (struct pbtools_message_base_t **)&self_p->bar_p,
                self_p->base.heap_p,
                sizeof(struct sub_message_pointers_message_bar_t),
                (pbtools_message_init_t)sub_message_pointers_message_bar_init));
}

void sub_message_pointers_message_message_fie_foo_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct sub_message_pointers_message_message_fie_foo_repeated_t *repeated_p)
{
    pbtools_encode_repeated_inner(
        encoder_p,
        field_number,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct sub_message_pointers_message_message_fie_foo_t),
        (pbtools_message_encode_inner_t)sub_message_pointers_message_message_fie_foo_encode_inner);
}

void sub_message_pointers_message_message_fie_foo_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct sub_message_pointers_message_message_fie_foo_repeated_t *repeated_p)
{
    pbtools_decode_repeated_inner(
        decoder_p,
        repeated_info_p,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct sub_message_pointers_message_message_fie_foo_t),
        (pbtools_message_init_t)sub_message_pointers_message_message_fie_foo_init,
        (pbtools_message_decode_inner_t)sub_message_pointers_message_message_fie_foo_decode_inner);
}

void sub_message_pointers_message_message_fie_init(
    struct sub_message_pointers_message_message_fie_t *self_p,
    struct pbtools_heap_t *heap_p)
{
    self_p->base.heap_p = heap_p;
    self_p->foo_p = NULL;
}

void sub_message_pointers_message_message_fie_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct sub_message_pointers_message_message_fie_t *self_p)
{
    pbtools_encoder_sub_message_pointer_encode(
        encoder_p,
        1,
        (struct pbtools_message_base_t *)self_p->foo_p,
        (pbtools_message_encode_inner_t)sub_message_pointers_message_message_fie_foo_encode_inner);
}

void sub_message_pointers_message_message_fie_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct sub_message_pointers_message_message_fie_t *self_p)
{
    int wire_type;

    while (pbtools_decoder_available(decoder_p)) {
        switch (pbtools_decoder_read_tag(decoder_p, &wire_type)) {

        case 1:
            pbtools_decoder_sub_message_pointer_decode(
                decoder_p,
                wire_type,
                (struct pbtools_message_base_t **)&self_p->foo_p,
                sizeof(struct sub_message_pointers_message_message_fie_foo_t),
                (pbtools_message_init_t)sub_message_pointers_message_message_fie_foo_init,
                (pbtools_message_decode_inner_t)sub_message_pointers_message_message_fie_foo_decode_inner);
            break;

        default:
            pbtools_decoder_skip_field(decoder_p, wire_type);
            break;
        }
    }
}

int sub_message_pointers_message_message_fie_foo_alloc(
    struct sub_message_pointers_message_message_fie_t *self_p)
{
    return (pbtools_sub_message_alloc(
                (struct pbtools_message_base_t **)&self_p->foo_p,
                self_p->base.heap_p,
                sizeof(struct sub_message_pointers_message_message_fie_foo_t),
                (pbtools_message_init_t)sub_message_pointers_message_message_fie_foo_init));
}

void sub_message_pointers_message_message_fie_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct sub_message_pointers_message_message_fie_repeated_t *repeated_p)
{
    pbtools_encode_repeated_inner(
        encoder_p,
        field_number,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct sub_message_pointers_message_message_fie_t),
        (pbtools_message_encode_inner_t)sub_message_pointers_message_message_fie_encode_inner);
}

void sub_message_pointers_message_message_fie_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct sub_message_pointers_message_message_fie_repeated_t *repeated_p)
{
    pbtools_decode_repeated_inner(
        decoder_p,
        repeated_info_p,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct sub_message_pointers_message_message_fie_t),
        (pbtools_message_init_t)sub_message_pointers_message_message_fie_init,
        (pbtools_message_decode_inner_t)sub_message_pointers_message_message_fie_decode_inner);
}

void sub_message_pointers_message_message_init(
    struct sub_message_pointers_message_message_t *self_p,
    struct pbtools_heap_t *heap_p)
{
    self_p->base.heap_p = heap_p;
    self_p->foo = 0;
    self_p->bar_p = NULL;
    self_p->fie_p = NULL;
}

void sub_message_pointers_message_message_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct sub_message_pointers_message_message_t *self_p)
{
    pbtools_encoder_sub_message_pointer_encode(
        encoder_p,
        4,
        (struct pbtools_message_base_t *)self_p->fie_p,
        (pbtools_message_encode_inner_t)sub_message_pointers_message_message_fie_encode_inner);
    pbtools_encoder_sub_message_pointer_encode(
        encoder_p,
        832,
        (struct pbtools_message_base_t *)self_p->bar_p,
        (pbtools_message_encode_inner_t)sub_message_pointers_message_bar_encode_inner);
    pbtools_encoder_write_enum(encoder_p, 1, self_p->foo);
}

void sub_message_pointers_message_message_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct sub_message_pointers_message_message_t *self_p)
{
    int wire_type;

    while (pbtools_decoder_available(decoder_p)) {
        switch (pbtools_decoder_read_tag(decoder_p, &wire_type)) {

        case 1:
            self_p->foo = pbtools_decoder_read_enum(decoder_p, wire_type);
            break;

        case 832:
            pbtools_decoder_sub_message_pointer_decode(
                decoder_p,
                wire_type,
                (struct pbtools_message_base_t **)&self_p->bar_p,
                sizeof(struct sub_message_pointers_message_bar_t),
                (pbtools_message_init_t)sub_message_pointers_message_bar_init,
                (pbtools_message_decode_inner_t)sub_message_pointers_message_bar_decode_inner);
            break;

        case 4:
            pbtools_decoder_sub_message_pointer_decode(
                decoder_p,
                wire_type,
                (struct pbtools_message_base_t **)&self_p->fie_p,
                sizeof(struct sub_message_pointers_message_message_fie_t),
                (pbtools_message_init_t)sub_message_pointers_message_message_fie_init,
                (pbtools_message_decode_inner_t)sub_message_pointers_message_message_fie_decode_inner);
            break;

        default:
            pbtools_decoder_skip_field(decoder_p, wire_type);
            break;
        }
    }
}

int sub_message_pointers_message_message_bar_alloc(
    struct sub_message_pointers_message_message_t *self_p)
{
    return (pbtools_sub_message_alloc(
                (struct pbtools_message_base_t **)&self_p->bar_p,
                self_p->base.heap_p,
                sizeof(struct sub_message_pointers_message_bar_t),
                (pbtools_message_init_t)sub_message_pointers_message_bar_init));
}

int sub_message_pointers_message_message_fie_alloc(
    struct sub_message_pointers_message_message_t *self_p)
{
    return (pbtools_sub_message_alloc(
                (struct pbtools_message_base_t **)&self_p->fie_p,
                self_p->base.heap_p,
                sizeof(struct sub_message_pointers_message_message_fie_t),
                (pbtools_message_init_t)sub_message_pointers_message_message_fie_init));
}

void sub_message_pointers_message_message_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct sub_message_pointers_message_message_repeated_t *repeated_p)
{
    pbtools_encode_repeated_inner(
        encoder_p,
        field_number,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct sub_message_pointers_message_message_t),
        (pbtools_message_encode_inner_t)sub_message_pointers_message_message_encode_inner);
}

void sub_message_pointers_message_message_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct sub_message_pointers_message_message_repeated_t *repeated_p)
{
    pbtools_decode_repeated_inner(
        decoder_p,
        repeated_info_p,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct sub_message_pointers_message_message_t),
        (pbtools_message_init_t)sub_message_pointers_message_message_init,
        (pbtools_message_decode_inner_t)sub_message_pointers_message_message_decode_inner);
}

struct sub_message_pointers_message_message_t *
sub_message_pointers_message_message_new(
    void *workspace_p,
    size_t size)
{
    return (pbtools_message_new(
                workspace_p,
                size,
                sizeof(struct sub_message_pointers_message_message_t),
                (pbtools_message_init_t)sub_message_pointers_message_message_init));
}

int sub_message_pointers_message_message_encode(
    struct sub_message_pointers_message_message_t *self_p,
    uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_encode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_encode_inner_t)sub_message_pointers_message_message_encode_inner));
}

int sub_message_pointers_message_message_decode(
    struct sub_message_pointers_message_message_t *self_p,
    const uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_decode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_decode_inner_t)sub_message_pointers_message_message_decode_inner));
}

void sub_message_pointers_message_unused_inner_types_unused_message_init(
    struct sub_message_pointers_message_unused_inner_types_unused_message_t *self_p,
    struct pbtools_heap_t *heap_p)
{
    self_p->base.heap_p = heap_p;
    self_p->v1 = 0;
}

void sub_message_pointers_message_unused_inner_types_unused_message_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct sub_message_pointers_message_unused_inner_types_unused_message_t *self_p)
{
    pbtools_encoder_write_bool(encoder_p, 1, self_p->v1);
}

void sub_message_pointers_message_unused_inner_types_unused_message_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct sub_message_pointers_message_unused_inner_types_unused_message_t *self_p)
{
    int wire_type;

    while (pbtools_decoder_available(decoder_p)) {
        switch (pbtools_decoder_read_tag(decoder_p, &wire_type)) {

        case 1:
            self_p->v1 = pbtools_decoder_read_bool(decoder_p, wire_type);
            break;

        default:
            pbtools_decoder_skip_field(decoder_p, wire_type);
            break;
        }
    }
}

void sub_message_pointers_message_unused_inner_types_unused_message_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct sub_message_pointers_message_unused_inner_types_unused_message_repeated_t *repeated_p)
{
    pbtools_encode_repeated_inner(
        encoder_p,
        field_number,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct sub_message_pointers_message_unused_inner_types_unused_message_t),
        (pbtools_message_encode_inner_t)sub_message_pointers_message_unused_inner_types_unused_message_encode_inner);
}

void sub_message_pointers_message_unused_inner_types_unused_message_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct sub_message_pointers_message_unused_inner_types_unused_message_repeated_t *repeated_p)
{
    pbtools_decode_repeated_inner(
        decoder_p,
        repeated_info_p,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct sub_message_pointers_message_unused_inner_types_unused_message_t),
        (pbtools_message_init_t)sub_message_pointers_message_unused_inner_types_unused_message_init,
        (pbtools_message_decode_inner_t)sub_message_pointers_message_unused_inner_types_unused_message_decode_inner);
}

void sub_message_pointers_message_unused_inner_types_init(
    struct sub_message_pointers_message_unused_inner_types_t *self_p,
    struct pbtools_heap_t *heap_p)
{
    self_p->base.heap_p = heap_p;
    self_p->v2 = 0;
}

void sub_message_pointers_message_unused_inner_types_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct sub_message_pointers_message_unused_inner_types_t *self_p)
{
    pbtools_encoder_write_bool(encoder_p, 1, self_p->v2);
}

void sub_message_pointers_message_unused_inner_types_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct sub_message_pointers_message_unused_inner_types_t *self_p)
{
    int wire_type;

    while (pbtools_decoder_available(decoder_p)) {
        switch (pbtools_decoder_read_tag(decoder_p, &wire_type)) {

        case 1:
            self_p->v2 = pbtools_decoder_read_bool(decoder_p, wire_type);
            break;

        default:
            pbtools_decoder_skip_field(decoder_p, wire_type);
            break;
        }
    }
}

void sub_message_pointers_message_unused_inner_types_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct sub_message_pointers_message_unused_inner_types_repeated_t *repeated_p)
{
    pbtools_encode_repeated_inner(
        encoder_p,
        field_number,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct sub_message_pointers_message_unused_inner_types_t),
        (pbtools_message_encode_inner_t)sub_message_pointers_message_unused_inner_types_encode_inner);
}

void sub_message_pointers_message_unused_inner_types_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct sub_message_pointers_message_unused_inner_types_repeated_t *repeated_p)
{
    pbtools_decode_repeated_inner(
        decoder_p,
        repeated_info_p,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct sub_message_pointers_message_unused_inner_types_t),
        (pbtools_message_init_t)sub_message_pointers_message_unused_inner_types_init,
        (pbtools_message_decode_inner_t)sub_message_pointers_message_unused_inner_types_decode_inner);
}

struct sub_message_pointers_message_unused_inner_types_t *
sub_message_pointers_message_unused_inner_types_new(
    void *workspace_p,
    size_t size)
{
    return (pbtools_message_new(
                workspace_p,
                size,
                sizeof(struct sub_message_pointers_message_unused_inner_types_t),
                (pbtools_message_init_t)sub_message_pointers_message_unused_inner_types_init));
}

int sub_message_pointers_message_unused_inner_types_encode(
    struct sub_message_pointers_message_unused_inner_types_t *self_p,
    uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_encode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_encode_inner_t)sub_message_pointers_message_unused_inner_types_encode_inner));
}

int sub_message_pointers_message_unused_inner_types_decode(
    struct sub_message_pointers_message_unused_inner_types_t *self_p,
    const uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_decode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_decode_inner_t)sub_message_pointers_message_unused_inner_types_decode_inner));
}
