/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by pbtools.
 */

#ifndef SUB_MESSAGE_POINTERS_REPEATED_H
#define SUB_MESSAGE_POINTERS_REPEATED_H

#ifdef __cplusplus
extern "C" {
#endif

#include "pbtools.h"

/**
 * Enum sub_message_pointers_repeated.Enum.
 */
enum sub_message_pointers_repeated_enum_e {
    sub_message_pointers_repeated_enum_a_e = 0,
    sub_message_pointers_repeated_enum_b_e = 1
};

/**
 * Message sub_message_pointers_repeated.Message.
 */
struct sub_message_pointers_repeated_message_repeated_t {
    int length;
    struct sub_message_pointers_repeated_message_t *items_p;
};

struct sub_message_pointers_repeated_message_t {
    struct pbtools_message_base_t base;
    struct pbtools_repeated_int32_t int32s;
    struct sub_message_pointers_repeated_message_repeated_t messages;
    struct pbtools_repeated_string_t strings;
    struct pbtools_repeated_bytes_t bytes;
};

/**
 * Message sub_message_pointers_repeated.MessageScalarValueTypes.
 */
struct sub_message_pointers_repeated_message_scalar_value_types_repeated_t {
    int length;
    struct sub_message_pointers_repeated_message_scalar_value_types_t *items_p;
};

struct sub_message_pointers_repeated_message_scalar_value_types_t {
    struct pbtools_message_base_t base;
    struct pbtools_repeated_int32_t int32s;
    struct pbtools_repeated_int64_t int64s;
    struct pbtools_repeated_int32_t sint32s;
    struct pbtools_repeated_int64_t sint64s;
    struct pbtools_repeated_uint32_t uint32s;
    struct pbtools_repeated_uint64_t uint64s;
    struct pbtools_repeated_uint32_t fixed32s;
    struct pbtools_repeated_uint64_t fixed64s;
    struct pbtools_repeated_int32_t sfixed32s;
    struct pbtools_repeated_int64_t sfixed64s;
    struct pbtools_repeated_float_t floats;
    struct pbtools_repeated_double_t doubles;
    struct pbtools_repeated_bool_t bools;
    struct pbtools_repeated_string_t strings;
    struct pbtools_repeated_bytes_t bytess;
};

/**
 * Message sub_message_pointers_repeated.MessageScalarValueTypesPacked.
 */
struct sub_message_pointers_repeated_message_scalar_value_types_packed_repeated_t {
    int length;
    struct sub_message_pointers_repeated_message_scalar_value_types_packed_t *items_p;
};

struct sub_message_pointers_repeated_message_scalar_value_types_packed_t {
    struct pbtools_message_base_t base;
    struct pbtools_repeated_int32_t int32s;
    struct pbtools_repeated_int64_t int64s;
    struct pbtools_repeated_int32_t sint32s;
    struct pbtools_repeated_int64_t sint64s;
    struct pbtools_repeated_uint32_t uint32s;
    struct pbtools_repeated_uint64_t uint64s;
    struct pbtools_repeated_uint32_t fixed32s;
    struct pbtools_repeated_uint64_t fixed64s;
    struct pbtools_repeated_int32_t sfixed32s;
    struct pbtools_repeated_int64_t sfixed64s;
    struct pbtools_repeated_float_t floats;
    struct pbtools_repeated_double_t doubles;
    struct pbtools_repeated_bool_t bools;
    struct pbtools_repeated_string_t strings;
    struct pbtools_repeated_bytes_t bytess;
};

/**
 * Message sub_message_pointers_repeated.MessageScalarValueTypesNotPacked.
 */
struct sub_message_pointers_repeated_message_scalar_value_types_not_packed_repeated_t {
    int length;
    struct sub_message_pointers_repeated_message_scalar_value_types_not_packed_t *items_p;
};

struct sub_message_pointers_repeated_message_scalar_value_types_not_packed_t {
    struct pbtools_message_base_t base;
    struct pbtools_repeated_int32_t int32s;
    struct pbtools_repeated_int64_t int64s;
    struct pbtools_repeated_int32_t sint32s;
    struct pbtools_repeated_int64_t sint64s;
    struct pbtools_repeated_uint32_t uint32s;
    struct pbtools_repeated_uint64_t uint64s;
    struct pbtools_repeated_uint32_t fixed32s;
    struct pbtools_repeated_uint64_t fixed64s;
    struct pbtools_repeated_int32_t sfixed32s;
    struct pbtools_repeated_int64_t sfixed64s;
    struct pbtools_repeated_float_t floats;
    struct pbtools_repeated_double_t doubles;
    struct pbtools_repeated_bool_t bools;
    struct pbtools_repeated_string_t strings;
    struct pbtools_repeated_bytes_t bytess;
};

/**
 * Message sub_message_pointers_repeated.Foo.
 */
struct sub_message_pointers_repeated_foo_repeated_t {
    int length;
    struct sub_message_pointers_repeated_foo_t *items_p;
};

struct sub_message_pointers_repeated_foo_t {
    struct pbtools_message_base_t base;
    struct sub_message_pointers_repeated_message_repeated_t messages;
    struct pbtools_repeated_int32_t enums;
};

/**
 * Message sub_message_pointers_repeated.Bar.Fie.
 */
struct sub_message_pointers_repeated_bar_fie_repeated_t {
    int length;
    struct sub_message_pointers_repeated_bar_fie_t *items_p;
};

struct sub_message_pointers_repeated_bar_fie_t {
    struct pbtools_message_base_t base;
    struct sub_message_pointers_repeated_foo_repeated_t inner_foos;
};

/**
 * Message sub_message_pointers_repeated.Bar.
 */
struct sub_message_pointers_repeated_bar_repeated_t {
    int length;
    struct sub_message_pointers_repeated_bar_t *items_p;
};

struct sub_message_pointers_repeated_bar_t {
    struct pbtools_message_base_t base;
    struct sub_message_pointers_repeated_foo_repeated_t foos;
    struct sub_message_pointers_repeated_bar_fie_repeated_t fies;
};

int sub_message_pointers_repeated_message_int32s_alloc(
    struct sub_message_pointers_repeated_message_t *self_p,
    int length);

int sub_message_pointers_repeated_message_messages_alloc(
    struct sub_message_pointers_repeated_message_t *self_p,
    int length);

int sub_message_pointers_repeated_message_strings_alloc(
    struct sub_message_pointers_repeated_message_t *self_p,
    int length);

int sub_message_pointers_repeated_message_bytes_alloc(
    struct sub_message_pointers_repeated_message_t *self_p,
    int length);

/**
 * Encoding and decoding of sub_message_pointers_repeated.Message.
 */
struct sub_message_pointers_repeated_message_t *
sub_message_pointers_repeated_message_new(
    void *workspace_p,
    size_t size);

int sub_message_pointers_repeated_message_encode(
    struct sub_message_pointers_repeated_message_t *self_p,
    uint8_t *encoded_p,
    size_t size);

int sub_message_pointers_repeated_message_decode(
    struct sub_message_pointers_repeated_message_t *self_p,
    const uint8_t *encoded_p,
    size_t size);

int sub_message_pointers_repeated_message_scalar_value_types_int32s_alloc(
    struct sub_message_pointers_repeated_message_scalar_value_types_t *self_p,
    int length);

int sub_message_pointers_repeated_message_scalar_value_types_int64s_alloc(
    struct sub_message_pointers_repeated_message_scalar_value_types_t *self_p,
    int length);

int sub_message_pointers_repeated_message_scalar_value_types_sint32s_alloc(
    struct sub_message_pointers_repeated_message_scalar_value_types_t *self_p,
    int length);

int sub_message_pointers_repeated_message_scalar_value_types_sint64s_alloc(
    struct sub_message_pointers_repeated_message_scalar_value_types_t *self_p,
    int length);

int sub_message_pointers_repeated_message_scalar_value_types_uint32s_alloc(
    struct sub_message_pointers_repeated_message_scalar_value_types_t *self_p,
    int length);

int sub_message_pointers_repeated_message_scalar_value_types_uint64s_alloc(
    struct sub_message_pointers_repeated_message_scalar_value_types_t *self_p,
    int length);

int sub_message_pointers_repeated_message_scalar_value_types_fixed32s_alloc(
    struct sub_message_pointers_repeated_message_scalar_value_types_t *self_p,
    int length);

int sub_message_pointers_repeated_message_scalar_value_types_fixed64s_alloc(
    struct sub_message_pointers_repeated_message_scalar_value_types_t *self_p,
    int length);

int sub_message_pointers_repeated_message_scalar_value_types_sfixed32s_alloc(
    struct sub_message_pointers_repeated_message_scalar_value_types_t *self_p,
    int length);

int sub_message_pointers_repeated_message_scalar_value_types_sfixed64s_alloc(
    struct sub_message_pointers_repeated_message_scalar_value_types_t *self_p,
    int length);

int sub_message_pointers_repeated_message_scalar_value_types_floats_alloc(
    struct sub_message_pointers_repeated_message_scalar_value_types_t *self_p,
    int length);

int sub_message_pointers_repeated_message_scalar_value_types_doubles_alloc(
    struct sub_message_pointers_repeated_message_scalar_value_types_t *self_p,
    int length);

int sub_message_pointers_repeated_message_scalar_value_types_bools_alloc(
    struct sub_message_pointers_repeated_message_scalar_value_types_t *self_p,
    int length);

int sub_message_pointers_repeated_message_scalar_value_types_strings_alloc(
    struct sub_message_pointers_repeated_message_scalar_value_types_t *self_p,
    int length);

int sub_message_pointers_repeated_message_scalar_value_types_bytess_alloc(
    struct sub_message_pointers_repeated_message_scalar_value_types_t *self_p,
    int length);

/**
 * Encoding and decoding of sub_message_pointers_repeated.MessageScalarValueTypes.
 */
struct sub_message_pointers_repeated_message_scalar_value_types_t *
sub_message_pointers_repeated_message_scalar_value_types_new(
    void *workspace_p,
    size_t size);

int sub_message_pointers_repeated_message_scalar_value_types_encode(
    struct sub_message_pointers_repeated_message_scalar_value_types_t *self_p,
    uint8_t *encoded_p,
    size_t size);

int sub_message_pointers_repeated_message_scalar_value_types_decode(
    struct sub_message_pointers_repeated_message_scalar_value_types_t *self_p,
    const uint8_t *encoded_p,
    size_t size);

int sub_message_pointers_repeated_message_scalar_value_types_packed_int32s_alloc(
    struct sub_message_pointers_repeated_message_scalar_value_types_packed_t *self_p,
    int length);

int sub_message_pointers_repeated_message_scalar_value_types_packed_int64s_alloc(
    struct sub_message_pointers_repeated_message_scalar_value_types_packed_t *self_p,
    int length);

int sub_message_pointers_repeated_message_scalar_value_types_packed_sint32s_alloc(
    struct sub_message_pointers_repeated_message_scalar_value_types_packed_t *self_p,
    int length);

int sub_message_pointers_repeated_message_scalar_value_types_packed_sint64s_alloc(
    struct sub_message_pointers_repeated_message_scalar_value_types_packed_t *self_p,
    int length);

int sub_message_pointers_repeated_message_scalar_value_types_packed_uint32s_alloc(
    struct sub_message_pointers_repeated_message_scalar_value_types_packed_t *self_p,
    int length);

int sub_message_pointers_repeated_message_scalar_value_types_packed_uint64s_alloc(
    struct sub_message_pointers_repeated_message_scalar_value_types_packed_t *self_p,
    int length);

int sub_message_pointers_repeated_message_scalar_value_types_packed_fixed32s_alloc(
    struct sub_message_pointers_repeated_message_scalar_value_types_packed_t *self_p,
    int length);

int sub_message_pointers_repeated_message_scalar_value_types_packed_fixed64s_alloc(
    struct sub_message_pointers_repeated_message_scalar_value_types_packed_t *self_p,
    int length);

int sub_message_pointers_repeated_message_scalar_value_types_packed_sfixed32s_alloc(
    struct sub_message_pointers_repeated_message_scalar_value_types_packed_t *self_p,
    int length);

int sub_message_pointers_repeated_message_scalar_value_types_packed_sfixed64s_alloc(
    struct sub_message_pointers_repeated_message_scalar_value_types_packed_t *self_p,
    int length);

int sub_message_pointers_repeated_message_scalar_value_types_packed_floats_alloc(
    struct sub_message_pointers_repeated_message_scalar_value_types_packed_t *self_p,
    int length);

int sub_message_pointers_repeated_message_scalar_value_types_packed_doubles_alloc(
    struct sub_message_pointers_repeated_message_scalar_value_types_packed_t *self_p,
    int length);

int sub_message_pointers_repeated_message_scalar_value_types_packed_bools_alloc(
    struct sub_message_pointers_repeated_message_scalar_value_types_packed_t *self_p,
    int length);

int sub_message_pointers_repeated_message_scalar_value_types_packed_strings_alloc(
    struct sub_message_pointers_repeated_message_scalar_value_types_packed_t *self_p,
    int length);

int sub_message_pointers_repeated_message_scalar_value_types_packed_bytess_alloc(
    struct sub_message_pointers_repeated_message_scalar_value_types_packed_t *self_p,
    int length);

/**
 * Encoding and decoding of sub_message_pointers_repeated.MessageScalarValueTypesPacked.
 */
struct sub_message_pointers_repeated_message_scalar_value_types_packed_t *
sub_message_pointers_repeated_message_scalar_value_types_packed_new(
    void *workspace_p,
    size_t size);

int sub_message_pointers_repeated_message_scalar_value_types_packed_encode(
    struct sub_message_pointers_repeated_message_scalar_value_types_packed_t *self_p,
    uint8_t *encoded_p,
    size_t size);

int sub_message_pointers_repeated_message_scalar_value_types_packed_decode(
    struct sub_message_pointers_repeated_message_scalar_value_types_packed_t *self_p,
    const uint8_t *encoded_p,
    size_t size);

int sub_message_pointers_repeated_message_scalar_value_types_not_packed_int32s_alloc(
    struct sub_message_pointers_repeated_message_scalar_value_types_not_packed_t *self_p,
    int length);

int sub_message_pointers_repeated_message_scalar_value_types_not_packed_int64s_alloc(
    struct sub_message_pointers_repeated_message_scalar_value_types_not_packed_t *self_p,
    int length);

int sub_message_pointers_repeated_message_scalar_value_types_not_packed_sint32s_alloc(
    struct sub_message_pointers_repeated_message_scalar_value_types_not_packed_t *self_p,
    int length);

int sub_message_pointers_repeated_message_scalar_value_types_not_packed_sint64s_alloc(
    struct sub_message_pointers_repeated_message_scalar_value_types_not_packed_t *self_p,
    int length);

int sub_message_pointers_repeated_message_scalar_value_types_not_packed_uint32s_alloc(
    struct sub_message_pointers_repeated_message_scalar_value_types_not_packed_t *self_p,
    int length);

int sub_message_pointers_repeated_message_scalar_value_types_not_packed_uint64s_alloc(
    struct sub_message_pointers_repeated_message_scalar_value_types_not_packed_t *self_p,
    int length);

int sub_message_pointers_repeated_message_scalar_value_types_not_packed_fixed32s_alloc(
    struct sub_message_pointers_repeated_message_scalar_value_types_not_packed_t *self_p,
    int length);

int sub_message_pointers_repeated_message_scalar_value_types_not_packed_fixed64s_alloc(
    struct sub_message_pointers_repeated_message_scalar_value_types_not_packed_t *self_p,
    int length);

int sub_message_pointers_repeated_message_scalar_value_types_not_packed_sfixed32s_alloc(
    struct sub_message_pointers_repeated_message_scalar_value_types_not_packed_t *self_p,
    int length);

int sub_message_pointers_repeated_message_scalar_value_types_not_packed_sfixed64s_alloc(
    struct sub_message_pointers_repeated_message_scalar_value_types_not_packed_t *self_p,
    int length);

int sub_message_pointers_repeated_message_scalar_value_types_not_packed_floats_alloc(
    struct sub_message_pointers_repeated_message_scalar_value_types_not_packed_t *self_p,
    int length);

int sub_message_pointers_repeated_message_scalar_value_types_not_packed_doubles_alloc(
    struct sub_message_pointers_repeated_message_scalar_value_types_not_packed_t *self_p,
    int length);

int sub_message_pointers_repeated_message_scalar_value_types_not_packed_bools_alloc(
    struct sub_message_pointers_repeated_message_scalar_value_types_not_packed_t *self_p,
    int length);

int sub_message_pointers_repeated_message_scalar_value_types_not_packed_strings_alloc(
    struct sub_message_pointers_repeated_message_scalar_value_types_not_packed_t *self_p,
    int length);

int sub_message_pointers_repeated_message_scalar_value_types_not_packed_bytess_alloc(
    struct sub_message_pointers_repeated_message_scalar_value_types_not_packed_t *self_p,
    int length);

/**
 * Encoding and decoding of sub_message_pointers_repeated.MessageScalarValueTypesNotPacked.
 */
struct sub_message_pointers_repeated_message_scalar_value_types_not_packed_t *
sub_message_pointers_repeated_message_scalar_value_types_not_packed_new(
    void *workspace_p,
    size_t size);

int sub_message_pointers_repeated_message_scalar_value_types_not_packed_encode(
    struct sub_message_pointers_repeated_message_scalar_value_types_not_packed_t *self_p,
    uint8_t *encoded_p,
    size_t size);

int sub_message_pointers_repeated_message_scalar_value_types_not_packed_decode(
    struct sub_message_pointers_repeated_message_scalar_value_types_not_packed_t *self_p,
    const uint8_t *encoded_p,
    size_t size);

int sub_message_pointers_repeated_foo_messages_alloc(
    struct sub_message_pointers_repeated_foo_t *self_p,
    int length);

int sub_message_pointers_repeated_foo_enums_alloc(
    struct sub_message_pointers_repeated_foo_t *self_p,
    int length);

/**
 * Encoding and decoding of sub_message_pointers_repeated.Foo.
 */
struct sub_message_pointers_repeated_foo_t *
sub_message_pointers_repeated_foo_new(
    void *workspace_p,
    size_t size);

int sub_message_pointers_repeated_foo_encode(
    struct sub_message_pointers_repeated_foo_t *self_p,
    uint8_t *encoded_p,
    size_t size);

int sub_message_pointers_repeated_foo_decode(
    struct sub_message_pointers_repeated_foo_t *self_p,
    const uint8_t *encoded_p,
    size_t size);

int sub_message_pointers_repeated_bar_foos_alloc(
    struct sub_message_pointers_repeated_bar_t *self_p,
    int length);

int sub_message_pointers_repeated_bar_fies_alloc(
    struct sub_message_pointers_repeated_bar_t *self_p,
    int length);

int sub_message_pointers_repeated_bar_fie_inner_foos_alloc(
    struct sub_message_pointers_repeated_bar_fie_t *self_p,
    int length);

/**
 * Encoding and decoding of sub_message_pointers_repeated.Bar.
 */
struct sub_message_pointers_repeated_bar_t *
sub_message_pointers_repeated_bar_new(
    void *workspace_p,
    size_t size);

int sub_message_pointers_repeated_bar_encode(
    struct sub_message_pointers_repeated_bar_t *self_p,
    uint8_t *encoded_p,
    size_t size);

int sub_message_pointers_repeated_bar_decode(
    struct sub_message_pointers_repeated_bar_t *self_p,
    const uint8_t *encoded_p,
    size_t size);

/* Internal functions. Do not use! */

void sub_message_pointers_repeated_message_init(
    struct sub_message_pointers_repeated_message_t *self_p,
    struct pbtools_heap_t *heap_p);

void sub_message_pointers_repeated_message_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct sub_message_pointers_repeated_message_t *self_p);

void sub_message_pointers_repeated_message_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct sub_message_pointers_repeated_message_t *self_p);

void sub_message_pointers_repeated_message_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct sub_message_pointers_repeated_message_repeated_t *repeated_p);

void sub_message_pointers_repeated_message_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct sub_message_pointers_repeated_message_repeated_t *repeated_p);

void sub_message_pointers_repeated_message_scalar_value_types_init(
    struct sub_message_pointers_repeated_message_scalar_value_types_t *self_p,
    struct pbtools_heap_t *heap_p);

void sub_message_pointers_repeated_message_scalar_value_types_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct sub_message_pointers_repeated_message_scalar_value_types_t *self_p);

void sub_message_pointers_repeated_message_scalar_value_types_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct sub_message_pointers_repeated_message_scalar_value_types_t *self_p);

void sub_message_pointers_repeated_message_scalar_value_types_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct sub_message_pointers_repeated_message_scalar_value_types_repeated_t *repeated_p);

void sub_message_pointers_repeated_message_scalar_value_types_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct sub_message_pointers_repeated_message_scalar_value_types_repeated_t *repeated_p);

void sub_message_pointers_repeated_message_scalar_value_types_packed_init(
    struct sub_message_pointers_repeated_message_scalar_value_types_packed_t *self_p,
    struct pbtools_heap_t *heap_p);

void sub_message_pointers_repeated_message_scalar_value_types_packed_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct sub_message_pointers_repeated_message_scalar_value_types_packed_t *self_p);

void sub_message_pointers_repeated_message_scalar_value_types_packed_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct sub_message_pointers_repeated_message_scalar_value_types_packed_t *self_p);

void sub_message_pointers_repeated_message_scalar_value_types_packed_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct sub_message_pointers_repeated_message_scalar_value_types_packed_repeated_t *repeated_p);

void sub_message_pointers_repeated_message_scalar_value_types_packed_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct sub_message_pointers_repeated_message_scalar_value_types_packed_repeated_t *repeated_p);

void sub_message_pointers_repeated_message_scalar_value_types_not_packed_init(
    struct sub_message_pointers_repeated_message_scalar_value_types_not_packed_t *self_p,
    struct pbtools_heap_t *heap_p);

void sub_message_pointers_repeated_message_scalar_value_types_not_packed_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct sub_message_pointers_repeated_message_scalar_value_types_not_packed_t *self_p);

void sub_message_pointers_repeated_message_scalar_value_types_not_packed_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct sub_message_pointers_repeated_message_scalar_value_types_not_packed_t *self_p);

void sub_message_pointers_repeated_message_scalar_value_types_not_packed_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct sub_message_pointers_repeated_message_scalar_value_types_not_packed_repeated_t *repeated_p);

void sub_message_pointers_repeated_message_scalar_value_types_not_packed_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct sub_message_pointers_repeated_message_scalar_value_types_not_packed_repeated_t *repeated_p);

void sub_message_pointers_repeated_foo_init(
    struct sub_message_pointers_repeated_foo_t *self_p,
    struct pbtools_heap_t *heap_p);

void sub_message_pointers_repeated_foo_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct sub_message_pointers_repeated_foo_t *self_p);

void sub_message_pointers_repeated_foo_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct sub_message_pointers_repeated_foo_t *self_p);

void sub_message_pointers_repeated_foo_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct sub_message_pointers_repeated_foo_repeated_t *repeated_p);

void sub_message_pointers_repeated_foo_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct sub_message_pointers_repeated_foo_repeated_t *repeated_p);

void sub_message_pointers_repeated_bar_init(
    struct sub_message_pointers_repeated_bar_t *self_p,
    struct pbtools_heap_t *heap_p);

void sub_message_pointers_repeated_bar_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct sub_message_pointers_repeated_bar_t *self_p);

void sub_message_pointers_repeated_bar_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct sub_message_pointers_repeated_bar_t *self_p);

void sub_message_pointers_repeated_bar_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct sub_message_pointers_repeated_bar_repeated_t *repeated_p);

void sub_message_pointers_repeated_bar_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct sub_message_pointers_repeated_bar_repeated_t *repeated_p);

void sub_message_pointers_repeated_bar_fie_init(
    struct sub_message_pointers_repeated_bar_fie_t *self_p,
    struct pbtools_heap_t *heap_p);

void sub_message_pointers_repeated_bar_fie_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct sub_message_pointers_repeated_bar_fie_t *self_p);

void sub_message_pointers_repeated_bar_fie_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct sub_message_pointers_repeated_bar_fie_t *self_p);

void sub_message_pointers_repeated_bar_fie_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct sub_message_pointers_repeated_bar_fie_repeated_t *repeated_p);

void sub_message_pointers_repeated_bar_fie_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct sub_message_pointers_repeated_bar_fie_repeated_t *repeated_p);

#ifdef __cplusplus
}
#endif

#endif
