/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by pbtools version 0.2.0 Tue Aug 27 22:08:14 2019.
 */

#include "tags.h"

static void tags_message1_encode_inner(
    struct tags_message1_t *self_p,
    struct pbtools_encoder_t *encoder_p)
{
    pbtools_encoder_write_bool(encoder_p, 1, self_p->value);
}

static void tags_message1_decode_inner(
    struct tags_message1_t *self_p,
    struct pbtools_decoder_t *decoder_p)
{
    int wire_type;

    while (pbtools_decoder_available(decoder_p)) {
        switch (pbtools_decoder_read_tag(decoder_p, &wire_type)) {

        case 1:
            self_p->value = pbtools_decoder_read_bool(decoder_p, wire_type);
            break;

        default:
            break;
        }
    }
}

struct tags_message1_t *tags_message1_new(
    void *workspace_p,
    size_t size)
{
    struct tags_message1_t *self_p;
    struct pbtools_heap_t *heap_p;

    heap_p = pbtools_heap_new(workspace_p, size);

    if (heap_p == NULL) {
        return (NULL);
    }

    self_p = pbtools_heap_alloc(heap_p, sizeof(*self_p));

    if (self_p != NULL) {
        self_p->heap_p = heap_p;
        self_p->value = 0;
    }

    return (self_p);
}

int tags_message1_encode(
    struct tags_message1_t *self_p,
    uint8_t *encoded_p,
    size_t size)
{
    struct pbtools_encoder_t encoder;

    pbtools_encoder_init(&encoder, encoded_p, size);
    tags_message1_encode_inner(self_p, &encoder);

    return (pbtools_encoder_get_result(&encoder));
}

int tags_message1_decode(
    struct tags_message1_t *self_p,
    const uint8_t *encoded_p,
    size_t size)
{
    struct pbtools_decoder_t decoder;

    pbtools_decoder_init(&decoder, encoded_p, size, self_p->heap_p);
    tags_message1_decode_inner(self_p, &decoder);

    return (pbtools_decoder_get_result(&decoder));
}

static void tags_message2_encode_inner(
    struct tags_message2_t *self_p,
    struct pbtools_encoder_t *encoder_p)
{
    pbtools_encoder_write_bool(encoder_p, 15, self_p->value);
}

static void tags_message2_decode_inner(
    struct tags_message2_t *self_p,
    struct pbtools_decoder_t *decoder_p)
{
    int wire_type;

    while (pbtools_decoder_available(decoder_p)) {
        switch (pbtools_decoder_read_tag(decoder_p, &wire_type)) {

        case 15:
            self_p->value = pbtools_decoder_read_bool(decoder_p, wire_type);
            break;

        default:
            break;
        }
    }
}

struct tags_message2_t *tags_message2_new(
    void *workspace_p,
    size_t size)
{
    struct tags_message2_t *self_p;
    struct pbtools_heap_t *heap_p;

    heap_p = pbtools_heap_new(workspace_p, size);

    if (heap_p == NULL) {
        return (NULL);
    }

    self_p = pbtools_heap_alloc(heap_p, sizeof(*self_p));

    if (self_p != NULL) {
        self_p->heap_p = heap_p;
        self_p->value = 0;
    }

    return (self_p);
}

int tags_message2_encode(
    struct tags_message2_t *self_p,
    uint8_t *encoded_p,
    size_t size)
{
    struct pbtools_encoder_t encoder;

    pbtools_encoder_init(&encoder, encoded_p, size);
    tags_message2_encode_inner(self_p, &encoder);

    return (pbtools_encoder_get_result(&encoder));
}

int tags_message2_decode(
    struct tags_message2_t *self_p,
    const uint8_t *encoded_p,
    size_t size)
{
    struct pbtools_decoder_t decoder;

    pbtools_decoder_init(&decoder, encoded_p, size, self_p->heap_p);
    tags_message2_decode_inner(self_p, &decoder);

    return (pbtools_decoder_get_result(&decoder));
}

static void tags_message3_encode_inner(
    struct tags_message3_t *self_p,
    struct pbtools_encoder_t *encoder_p)
{
    pbtools_encoder_write_bool(encoder_p, 16, self_p->value);
}

static void tags_message3_decode_inner(
    struct tags_message3_t *self_p,
    struct pbtools_decoder_t *decoder_p)
{
    int wire_type;

    while (pbtools_decoder_available(decoder_p)) {
        switch (pbtools_decoder_read_tag(decoder_p, &wire_type)) {

        case 16:
            self_p->value = pbtools_decoder_read_bool(decoder_p, wire_type);
            break;

        default:
            break;
        }
    }
}

struct tags_message3_t *tags_message3_new(
    void *workspace_p,
    size_t size)
{
    struct tags_message3_t *self_p;
    struct pbtools_heap_t *heap_p;

    heap_p = pbtools_heap_new(workspace_p, size);

    if (heap_p == NULL) {
        return (NULL);
    }

    self_p = pbtools_heap_alloc(heap_p, sizeof(*self_p));

    if (self_p != NULL) {
        self_p->heap_p = heap_p;
        self_p->value = 0;
    }

    return (self_p);
}

int tags_message3_encode(
    struct tags_message3_t *self_p,
    uint8_t *encoded_p,
    size_t size)
{
    struct pbtools_encoder_t encoder;

    pbtools_encoder_init(&encoder, encoded_p, size);
    tags_message3_encode_inner(self_p, &encoder);

    return (pbtools_encoder_get_result(&encoder));
}

int tags_message3_decode(
    struct tags_message3_t *self_p,
    const uint8_t *encoded_p,
    size_t size)
{
    struct pbtools_decoder_t decoder;

    pbtools_decoder_init(&decoder, encoded_p, size, self_p->heap_p);
    tags_message3_decode_inner(self_p, &decoder);

    return (pbtools_decoder_get_result(&decoder));
}

static void tags_message4_encode_inner(
    struct tags_message4_t *self_p,
    struct pbtools_encoder_t *encoder_p)
{
    pbtools_encoder_write_bool(encoder_p, 2047, self_p->value);
}

static void tags_message4_decode_inner(
    struct tags_message4_t *self_p,
    struct pbtools_decoder_t *decoder_p)
{
    int wire_type;

    while (pbtools_decoder_available(decoder_p)) {
        switch (pbtools_decoder_read_tag(decoder_p, &wire_type)) {

        case 2047:
            self_p->value = pbtools_decoder_read_bool(decoder_p, wire_type);
            break;

        default:
            break;
        }
    }
}

struct tags_message4_t *tags_message4_new(
    void *workspace_p,
    size_t size)
{
    struct tags_message4_t *self_p;
    struct pbtools_heap_t *heap_p;

    heap_p = pbtools_heap_new(workspace_p, size);

    if (heap_p == NULL) {
        return (NULL);
    }

    self_p = pbtools_heap_alloc(heap_p, sizeof(*self_p));

    if (self_p != NULL) {
        self_p->heap_p = heap_p;
        self_p->value = 0;
    }

    return (self_p);
}

int tags_message4_encode(
    struct tags_message4_t *self_p,
    uint8_t *encoded_p,
    size_t size)
{
    struct pbtools_encoder_t encoder;

    pbtools_encoder_init(&encoder, encoded_p, size);
    tags_message4_encode_inner(self_p, &encoder);

    return (pbtools_encoder_get_result(&encoder));
}

int tags_message4_decode(
    struct tags_message4_t *self_p,
    const uint8_t *encoded_p,
    size_t size)
{
    struct pbtools_decoder_t decoder;

    pbtools_decoder_init(&decoder, encoded_p, size, self_p->heap_p);
    tags_message4_decode_inner(self_p, &decoder);

    return (pbtools_decoder_get_result(&decoder));
}

static void tags_message5_encode_inner(
    struct tags_message5_t *self_p,
    struct pbtools_encoder_t *encoder_p)
{
    pbtools_encoder_write_bool(encoder_p, 2048, self_p->value);
}

static void tags_message5_decode_inner(
    struct tags_message5_t *self_p,
    struct pbtools_decoder_t *decoder_p)
{
    int wire_type;

    while (pbtools_decoder_available(decoder_p)) {
        switch (pbtools_decoder_read_tag(decoder_p, &wire_type)) {

        case 2048:
            self_p->value = pbtools_decoder_read_bool(decoder_p, wire_type);
            break;

        default:
            break;
        }
    }
}

struct tags_message5_t *tags_message5_new(
    void *workspace_p,
    size_t size)
{
    struct tags_message5_t *self_p;
    struct pbtools_heap_t *heap_p;

    heap_p = pbtools_heap_new(workspace_p, size);

    if (heap_p == NULL) {
        return (NULL);
    }

    self_p = pbtools_heap_alloc(heap_p, sizeof(*self_p));

    if (self_p != NULL) {
        self_p->heap_p = heap_p;
        self_p->value = 0;
    }

    return (self_p);
}

int tags_message5_encode(
    struct tags_message5_t *self_p,
    uint8_t *encoded_p,
    size_t size)
{
    struct pbtools_encoder_t encoder;

    pbtools_encoder_init(&encoder, encoded_p, size);
    tags_message5_encode_inner(self_p, &encoder);

    return (pbtools_encoder_get_result(&encoder));
}

int tags_message5_decode(
    struct tags_message5_t *self_p,
    const uint8_t *encoded_p,
    size_t size)
{
    struct pbtools_decoder_t decoder;

    pbtools_decoder_init(&decoder, encoded_p, size, self_p->heap_p);
    tags_message5_decode_inner(self_p, &decoder);

    return (pbtools_decoder_get_result(&decoder));
}

static void tags_message6_encode_inner(
    struct tags_message6_t *self_p,
    struct pbtools_encoder_t *encoder_p)
{
    pbtools_encoder_write_bool(encoder_p, 536870911, self_p->value);
}

static void tags_message6_decode_inner(
    struct tags_message6_t *self_p,
    struct pbtools_decoder_t *decoder_p)
{
    int wire_type;

    while (pbtools_decoder_available(decoder_p)) {
        switch (pbtools_decoder_read_tag(decoder_p, &wire_type)) {

        case 536870911:
            self_p->value = pbtools_decoder_read_bool(decoder_p, wire_type);
            break;

        default:
            break;
        }
    }
}

struct tags_message6_t *tags_message6_new(
    void *workspace_p,
    size_t size)
{
    struct tags_message6_t *self_p;
    struct pbtools_heap_t *heap_p;

    heap_p = pbtools_heap_new(workspace_p, size);

    if (heap_p == NULL) {
        return (NULL);
    }

    self_p = pbtools_heap_alloc(heap_p, sizeof(*self_p));

    if (self_p != NULL) {
        self_p->heap_p = heap_p;
        self_p->value = 0;
    }

    return (self_p);
}

int tags_message6_encode(
    struct tags_message6_t *self_p,
    uint8_t *encoded_p,
    size_t size)
{
    struct pbtools_encoder_t encoder;

    pbtools_encoder_init(&encoder, encoded_p, size);
    tags_message6_encode_inner(self_p, &encoder);

    return (pbtools_encoder_get_result(&encoder));
}

int tags_message6_decode(
    struct tags_message6_t *self_p,
    const uint8_t *encoded_p,
    size_t size)
{
    struct pbtools_decoder_t decoder;

    pbtools_decoder_init(&decoder, encoded_p, size, self_p->heap_p);
    tags_message6_decode_inner(self_p, &decoder);

    return (pbtools_decoder_get_result(&decoder));
}
